const data = {
    products :[
        {
            id:'1',
            name:'slim shirt',
            image:'./images/product-1.jpg',
            price:'80',
            brand:'NIKE',
            rating: '4.5',
            numReview:'10',
            description:'high quality product',
        },
        {
            id:'2',
            name:'skin shirt',
            image:'./images/product-1.jpg',
            price:'10',
            brand:'GENERIC',
            rating: '4',
            numReview:'500',
            description:'high quality product',
        },
        {
            id:'3',
            name:'long shirt',
            image:'./images/product-1.jpg',
            price:'30',
            brand:'MAX',
            rating: '5',
            numReview:'6',
            description:'high quality product',
        },
        {
            id:'4',
            name:'long sleeve shirt',
            image:'./images/product-1.jpg',
            price:'100',
            brand:'PUMA',
            rating: '4',
            numReview:'13',
            description:'high quality product',
        },
        {
            id:'5',
            name:'shirt',
            image:'./images/product-1.jpg',
            price:'120',
            brand:'ADIDAS',
            rating: '4',
            numReview:'30',
            description:'high quality product',
        },
        {
            id:'6',
            name:'Graphic shirt',
            image:'./images/product-1.jpg',
            price:'490',
            brand:'GUCCI',
            rating: '4.5',
            numReview:'100',
            description:'high quality product',
        },
    ]
};
export default data;